LOCAL_PATH  := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := icuuc51
ICU_DIR=../icu4c/source
LOCAL_CFLAGS += -D_REENTRANT -DU_COMMON_IMPLEMENTATION -DU_HAVE_NL_LANGINFO_CODESET=0 -DU_TIMEZONE=timezone -frtti -fno-exceptions -O3 -fvisibility=hidden -DPIC -fPIC
LOCAL_C_INCLUDES := $(ICU_DIR)/common $(ICU_DIR)/i18n
LOCAL_LDLIBS := -ldl -lm
LOCAL_RTTI_FLAG := -frtti
LOCAL_SHARED_LIBRARIES += libgabi++ libdl
LOCAL_SRC_FILES :=  $(ICU_DIR)/common/errorcode.cpp \
                    $(ICU_DIR)/common/putil.cpp \
   					$(ICU_DIR)/common/umath.c \
   					$(ICU_DIR)/common/utypes.c \
   					$(ICU_DIR)/common/uinvchar.c \
                    $(ICU_DIR)/common/umutex.cpp \
   					$(ICU_DIR)/common/ucln_cmn.c \
                    $(ICU_DIR)/common/uinit.c \
                    $(ICU_DIR)/common/uobject.cpp \
                    $(ICU_DIR)/common/cmemory.c \
                    $(ICU_DIR)/common/charstr.cpp \
                    $(ICU_DIR)/common/udata.cpp \
                    $(ICU_DIR)/common/ucmndata.c \
                    $(ICU_DIR)/common/udatamem.c \
                    $(ICU_DIR)/common/umapfile.c \
                    $(ICU_DIR)/common/udataswp.c \
                    $(ICU_DIR)/common/ucol_swp.cpp \
                    $(ICU_DIR)/common/utrace.c \
                    $(ICU_DIR)/common/uhash.c \
                    $(ICU_DIR)/common/uhash_us.cpp \
                    $(ICU_DIR)/common/uenum.c \
                    $(ICU_DIR)/common/ustrenum.cpp \
                    $(ICU_DIR)/common/uvector.cpp \
                    $(ICU_DIR)/common/ustack.cpp \
                    $(ICU_DIR)/common/uvectr32.cpp \
                    $(ICU_DIR)/common/uvectr64.cpp \
                    $(ICU_DIR)/common/ucnv.c \
                    $(ICU_DIR)/common/ucnv_bld.cpp \
                    $(ICU_DIR)/common/ucnv_cnv.c \
                    $(ICU_DIR)/common/ucnv_io.cpp \
                    $(ICU_DIR)/common/ucnv_cb.c \
                    $(ICU_DIR)/common/ucnv_err.c \
                    $(ICU_DIR)/common/ucnvlat1.c \
                    $(ICU_DIR)/common/ucnv_u7.c \
                    $(ICU_DIR)/common/ucnv_u8.c \
                    $(ICU_DIR)/common/ucnv_u16.c \
                    $(ICU_DIR)/common/ucnv_u32.c \
                    $(ICU_DIR)/common/ucnvscsu.c \
                    $(ICU_DIR)/common/ucnvbocu.cpp \
                    $(ICU_DIR)/common/ucnv_ext.cpp \
                    $(ICU_DIR)/common/ucnvmbcs.c \
                    $(ICU_DIR)/common/ucnv2022.cpp \
                    $(ICU_DIR)/common/ucnvhz.c \
                    $(ICU_DIR)/common/ucnv_lmb.c \
                    $(ICU_DIR)/common/ucnvisci.c \
                    $(ICU_DIR)/common/ucnvdisp.c \
                    $(ICU_DIR)/common/ucnv_set.c \
                    $(ICU_DIR)/common/ucnv_ct.c \
                    $(ICU_DIR)/common/uresbund.cpp \
                    $(ICU_DIR)/common/ures_cnv.c \
                    $(ICU_DIR)/common/uresdata.c \
                    $(ICU_DIR)/common/resbund.cpp \
                    $(ICU_DIR)/common/resbund_cnv.cpp \
                    $(ICU_DIR)/common/messagepattern.cpp \
                    $(ICU_DIR)/common/ucat.c \
                    $(ICU_DIR)/common/locmap.c \
                    $(ICU_DIR)/common/uloc.cpp \
                    $(ICU_DIR)/common/locid.cpp \
                    $(ICU_DIR)/common/locutil.cpp \
                    $(ICU_DIR)/common/locavailable.cpp \
                    $(ICU_DIR)/common/locdispnames.cpp \
                    $(ICU_DIR)/common/loclikely.cpp \
                    $(ICU_DIR)/common/locresdata.cpp \
                    $(ICU_DIR)/common/bytestream.cpp \
                    $(ICU_DIR)/common/stringpiece.cpp \
                    $(ICU_DIR)/common/stringtriebuilder.cpp \
                    $(ICU_DIR)/common/bytestriebuilder.cpp \
                    $(ICU_DIR)/common/bytestrie.cpp \
                    $(ICU_DIR)/common/bytestrieiterator.cpp \
                    $(ICU_DIR)/common/ucharstrie.cpp \
                    $(ICU_DIR)/common/ucharstriebuilder.cpp \
                    $(ICU_DIR)/common/ucharstrieiterator.cpp \
                    $(ICU_DIR)/common/dictionarydata.cpp \
                    $(ICU_DIR)/common/appendable.cpp \
                    $(ICU_DIR)/common/ustr_cnv.c \
                    $(ICU_DIR)/common/unistr_cnv.cpp \
                    $(ICU_DIR)/common/unistr.cpp \
                    $(ICU_DIR)/common/unistr_case.cpp \
                    $(ICU_DIR)/common/unistr_props.cpp \
                    $(ICU_DIR)/common/utf_impl.c \
                    $(ICU_DIR)/common/ustring.cpp \
                    $(ICU_DIR)/common/ustrcase.cpp \
                    $(ICU_DIR)/common/ucasemap.cpp \
                    $(ICU_DIR)/common/ucasemap_titlecase_brkiter.cpp \
                    $(ICU_DIR)/common/cstring.c \
                    $(ICU_DIR)/common/ustrfmt.c \
                    $(ICU_DIR)/common/ustrtrns.cpp \
                    $(ICU_DIR)/common/ustr_wcs.cpp \
                    $(ICU_DIR)/common/utext.cpp \
                    $(ICU_DIR)/common/unistr_case_locale.cpp \
                    $(ICU_DIR)/common/ustrcase_locale.cpp \
                    $(ICU_DIR)/common/unistr_titlecase_brkiter.cpp \
                    $(ICU_DIR)/common/ustr_titlecase_brkiter.cpp \
                    $(ICU_DIR)/common/normalizer2impl.cpp \
                    $(ICU_DIR)/common/normalizer2.cpp \
                    $(ICU_DIR)/common/filterednormalizer2.cpp \
                    $(ICU_DIR)/common/normlzr.cpp \
                    $(ICU_DIR)/common/unorm.cpp \
                    $(ICU_DIR)/common/unormcmp.cpp \
                    $(ICU_DIR)/common/unorm_it.c \
                    $(ICU_DIR)/common/chariter.cpp \
                    $(ICU_DIR)/common/schriter.cpp \
                    $(ICU_DIR)/common/uchriter.cpp \
                    $(ICU_DIR)/common/uiter.cpp \
                    $(ICU_DIR)/common/patternprops.cpp \
                    $(ICU_DIR)/common/uchar.c \
                    $(ICU_DIR)/common/uprops.cpp \
                    $(ICU_DIR)/common/ucase.cpp \
                    $(ICU_DIR)/common/propname.cpp \
                    $(ICU_DIR)/common/ubidi_props.c \
                    $(ICU_DIR)/common/ubidi.c \
                    $(ICU_DIR)/common/ubidiwrt.c \
                    $(ICU_DIR)/common/ubidiln.c \
                    $(ICU_DIR)/common/ushape.cpp \
                    $(ICU_DIR)/common/uscript.c \
                    $(ICU_DIR)/common/uscript_props.cpp \
                    $(ICU_DIR)/common/usc_impl.c \
                    $(ICU_DIR)/common/unames.cpp \
                    $(ICU_DIR)/common/utrie.cpp \
                    $(ICU_DIR)/common/utrie2.cpp \
                    $(ICU_DIR)/common/utrie2_builder.cpp \
                    $(ICU_DIR)/common/bmpset.cpp \
                    $(ICU_DIR)/common/unisetspan.cpp \
                    $(ICU_DIR)/common/uset_props.cpp \
                    $(ICU_DIR)/common/uniset_props.cpp \
                    $(ICU_DIR)/common/uniset_closure.cpp \
                    $(ICU_DIR)/common/uset.cpp \
                    $(ICU_DIR)/common/uniset.cpp \
                    $(ICU_DIR)/common/usetiter.cpp \
                    $(ICU_DIR)/common/ruleiter.cpp \
                    $(ICU_DIR)/common/caniter.cpp \
                    $(ICU_DIR)/common/unifilt.cpp \
                    $(ICU_DIR)/common/unifunct.cpp \
                    $(ICU_DIR)/common/uarrsort.c \
                    $(ICU_DIR)/common/brkiter.cpp \
                    $(ICU_DIR)/common/ubrk.cpp \
                    $(ICU_DIR)/common/brkeng.cpp \
                    $(ICU_DIR)/common/dictbe.cpp \
                    $(ICU_DIR)/common/rbbi.cpp \
                    $(ICU_DIR)/common/rbbidata.cpp \
                    $(ICU_DIR)/common/rbbinode.cpp \
                    $(ICU_DIR)/common/rbbirb.cpp \
                    $(ICU_DIR)/common/rbbiscan.cpp \
                    $(ICU_DIR)/common/rbbisetb.cpp \
                    $(ICU_DIR)/common/rbbistbl.cpp \
                    $(ICU_DIR)/common/rbbitblb.cpp \
                    $(ICU_DIR)/common/serv.cpp \
                    $(ICU_DIR)/common/servnotf.cpp \
                    $(ICU_DIR)/common/servls.cpp \
                    $(ICU_DIR)/common/servlk.cpp \
                    $(ICU_DIR)/common/servlkf.cpp \
                    $(ICU_DIR)/common/servrbf.cpp \
                    $(ICU_DIR)/common/servslkf.cpp \
                    $(ICU_DIR)/common/uidna.cpp \
                    $(ICU_DIR)/common/usprep.cpp \
                    $(ICU_DIR)/common/uts46.cpp \
                    $(ICU_DIR)/common/punycode.cpp \
                    $(ICU_DIR)/common/util.cpp \
                    $(ICU_DIR)/common/util_props.cpp \
                    $(ICU_DIR)/common/parsepos.cpp \
                    $(ICU_DIR)/common/locbased.cpp \
                    $(ICU_DIR)/common/cwchar.c \
                    $(ICU_DIR)/common/wintz.c \
                    $(ICU_DIR)/common/mutex.cpp \
                    $(ICU_DIR)/common/dtintrv.cpp \
                    $(ICU_DIR)/common/ucnvsel.cpp \
                    $(ICU_DIR)/common/propsvec.c \
                    $(ICU_DIR)/common/ulist.c \
                    $(ICU_DIR)/common/uloc_tag.c \
                    $(ICU_DIR)/common/icudataver.c \
                    $(ICU_DIR)/common/icuplug.c \
                    $(ICU_DIR)/common/listformatter.cpp

LOCAL_SHARED_LIBRARIES  := icudt51

include $(BUILD_SHARED_LIBRARY)

